name: Build
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  errors-check:
    name: Check for errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: TSC Check
        run: yarn tsc-check
  bundle:
    if: ${{ github.event_name != 'pull_request' }}
    needs: errors-check
    name: Bundle and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Bundle
        run: yarn bundle
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
