name: Lint
on: [pull_request, push]

jobs:
  prettier:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prettier Check
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: "--write ."
          dry: true
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: ESLint Check
        run: yarn lint
